package com.nicola.wakemup.utils

import android.Manifest


private val PACKAGE_NAME = "com.nicola.wakemup"

const val PERMISSION_FINE_LOCATION = Manifest.permission.ACCESS_FINE_LOCATION
const val PERMISSION_BACKGROUND_LOCATION = Manifest.permission.ACCESS_BACKGROUND_LOCATION
const val PERMISSION_LOCATION_CODE = 372

val LOCATION_SETTINGS = 555

val INVALID_FLOAT_VALUE = -999.0F
val INVALID_DOUBLE_VALUE = -999.0

val FETCH_ADDRESS = 364
val RECEIVER = PACKAGE_NAME + ".RECEIVER"
val RESULT_DATA_KEY = PACKAGE_NAME + ".RESULT_DATA_KEY"
val LOCATION_DATA_EXTRA = PACKAGE_NAME + ".LOCATION_DATA_EXTRA"

val NOTIFICATION_ID = 999
val START_ALARM = PACKAGE_NAME + ".START_ALARM"
val STOP_ALARM = PACKAGE_NAME + ".STOP_ALARM"
